# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'analysis.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractButton, QAbstractScrollArea, QApplication, QCheckBox,
    QDialogButtonBox, QDoubleSpinBox, QHeaderView, QLabel,
    QSizePolicy, QSpinBox, QTabWidget, QTableView,
    QWidget)

class Ui_analysisDialog(object):
    def setupUi(self, analysisDialog):
        if not analysisDialog.objectName():
            analysisDialog.setObjectName(u"analysisDialog")
        analysisDialog.setWindowModality(Qt.ApplicationModal)
        analysisDialog.resize(617, 417)
        self.tabWidget = QTabWidget(analysisDialog)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(10, 10, 591, 331))
        self.basicTab = QWidget()
        self.basicTab.setObjectName(u"basicTab")
        self.analysisTableView = QTableView(self.basicTab)
        self.analysisTableView.setObjectName(u"analysisTableView")
        self.analysisTableView.setGeometry(QRect(10, 10, 561, 271))
        self.analysisTableView.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.analysisTableView.setAlternatingRowColors(True)
        self.tabWidget.addTab(self.basicTab, "")
        self.preprocessTab = QWidget()
        self.preprocessTab.setObjectName(u"preprocessTab")
        self.medianFilterCheckBox = QCheckBox(self.preprocessTab)
        self.medianFilterCheckBox.setObjectName(u"medianFilterCheckBox")
        self.medianFilterCheckBox.setGeometry(QRect(10, 10, 391, 27))
        self.medianFilterSpinBox = QSpinBox(self.preprocessTab)
        self.medianFilterSpinBox.setObjectName(u"medianFilterSpinBox")
        self.medianFilterSpinBox.setEnabled(True)
        self.medianFilterSpinBox.setGeometry(QRect(220, 40, 60, 21))
        self.medianFilterSpinBox.setMinimum(1)
        self.medianFilterSpinBox.setMaximum(100)
        self.medianFilterSpinBox.setSingleStep(1)
        self.medianFilterSpinBox.setValue(4)
        self.shrinkCheckBox = QCheckBox(self.preprocessTab)
        self.shrinkCheckBox.setObjectName(u"shrinkCheckBox")
        self.shrinkCheckBox.setGeometry(QRect(10, 60, 331, 22))
        self.shrinkDoubleSpinBox = QDoubleSpinBox(self.preprocessTab)
        self.shrinkDoubleSpinBox.setObjectName(u"shrinkDoubleSpinBox")
        self.shrinkDoubleSpinBox.setEnabled(True)
        self.shrinkDoubleSpinBox.setGeometry(QRect(220, 90, 60, 21))
        self.shrinkDoubleSpinBox.setMaximum(100.000000000000000)
        self.shrinkDoubleSpinBox.setSingleStep(0.100000000000000)
        self.shrinkDoubleSpinBox.setValue(0.500000000000000)
        self.filterWindowSizeLabel = QLabel(self.preprocessTab)
        self.filterWindowSizeLabel.setObjectName(u"filterWindowSizeLabel")
        self.filterWindowSizeLabel.setEnabled(False)
        self.filterWindowSizeLabel.setGeometry(QRect(30, 40, 161, 18))
        self.shrinkNewdTValueLabel = QLabel(self.preprocessTab)
        self.shrinkNewdTValueLabel.setObjectName(u"shrinkNewdTValueLabel")
        self.shrinkNewdTValueLabel.setEnabled(False)
        self.shrinkNewdTValueLabel.setGeometry(QRect(30, 90, 151, 18))
        self.labelTempRangeMin = QLabel(self.preprocessTab)
        self.labelTempRangeMin.setObjectName(u"labelTempRangeMin")
        self.labelTempRangeMin.setGeometry(QRect(10, 120, 401, 18))
        self.labelTempRangeMax = QLabel(self.preprocessTab)
        self.labelTempRangeMax.setObjectName(u"labelTempRangeMax")
        self.labelTempRangeMax.setGeometry(QRect(10, 170, 401, 18))
        self.tempRangeMaxSpinBox = QSpinBox(self.preprocessTab)
        self.tempRangeMaxSpinBox.setObjectName(u"tempRangeMaxSpinBox")
        self.tempRangeMaxSpinBox.setGeometry(QRect(10, 190, 51, 30))
        self.tempRangeMaxSpinBox.setValue(0)
        self.tempRangeMinSpinBox = QSpinBox(self.preprocessTab)
        self.tempRangeMinSpinBox.setObjectName(u"tempRangeMinSpinBox")
        self.tempRangeMinSpinBox.setGeometry(QRect(10, 140, 51, 30))
        self.tempRangeMinSpinBox.setValue(0)
        self.tabWidget.addTab(self.preprocessTab, "")
        self.miscTab = QWidget()
        self.miscTab.setObjectName(u"miscTab")
        self.savgolSpinBox = QSpinBox(self.miscTab)
        self.savgolSpinBox.setObjectName(u"savgolSpinBox")
        self.savgolSpinBox.setGeometry(QRect(10, 40, 61, 21))
        self.savgolSpinBox.setMinimum(1)
        self.savgolSpinBox.setMaximum(100)
        self.savgolSpinBox.setSingleStep(1)
        self.savgolSpinBox.setValue(10)
        self.savgolLabel = QLabel(self.miscTab)
        self.savgolLabel.setObjectName(u"savgolLabel")
        self.savgolLabel.setGeometry(QRect(10, 10, 401, 18))
        self.baselineFitLabel = QLabel(self.miscTab)
        self.baselineFitLabel.setObjectName(u"baselineFitLabel")
        self.baselineFitLabel.setGeometry(QRect(10, 70, 381, 18))
        self.baselineFitSpinBox = QSpinBox(self.miscTab)
        self.baselineFitSpinBox.setObjectName(u"baselineFitSpinBox")
        self.baselineFitSpinBox.setGeometry(QRect(10, 100, 61, 21))
        self.baselineFitSpinBox.setMinimum(1)
        self.baselineFitSpinBox.setMaximum(100)
        self.baselineFitSpinBox.setSingleStep(1)
        self.baselineFitSpinBox.setValue(10)
        self.baselineBoundsLabel = QLabel(self.miscTab)
        self.baselineBoundsLabel.setObjectName(u"baselineBoundsLabel")
        self.baselineBoundsLabel.setGeometry(QRect(10, 130, 381, 18))
        self.baselineBoundsSpinbox = QSpinBox(self.miscTab)
        self.baselineBoundsSpinbox.setObjectName(u"baselineBoundsSpinbox")
        self.baselineBoundsSpinbox.setGeometry(QRect(10, 160, 70, 21))
        self.baselineBoundsSpinbox.setMinimum(0)
        self.baselineBoundsSpinbox.setMaximum(100)
        self.baselineBoundsSpinbox.setSingleStep(1)
        self.baselineBoundsSpinbox.setValue(3)
        self.dCpLabel = QLabel(self.miscTab)
        self.dCpLabel.setObjectName(u"dCpLabel")
        self.dCpLabel.setGeometry(QRect(10, 190, 401, 18))
        self.dCpSpinBox = QSpinBox(self.miscTab)
        self.dCpSpinBox.setObjectName(u"dCpSpinBox")
        self.dCpSpinBox.setEnabled(True)
        self.dCpSpinBox.setGeometry(QRect(10, 220, 61, 21))
        self.dCpSpinBox.setMinimum(0)
        self.dCpSpinBox.setMaximum(10000)
        self.dCpSpinBox.setSingleStep(1)
        self.dCpSpinBox.setValue(0)
        self.tabWidget.addTab(self.miscTab, "")
        self.buttonBox = QDialogButtonBox(analysisDialog)
        self.buttonBox.setObjectName(u"buttonBox")
        self.buttonBox.setGeometry(QRect(10, 360, 591, 25))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setStandardButtons(QDialogButtonBox.Cancel|QDialogButtonBox.Ok|QDialogButtonBox.RestoreDefaults)
        self.buttonBox.setCenterButtons(False)

        self.retranslateUi(analysisDialog)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(analysisDialog)
    # setupUi

    def retranslateUi(self, analysisDialog):
        analysisDialog.setWindowTitle(QCoreApplication.translate("analysisDialog", u"Analysis", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.basicTab), QCoreApplication.translate("analysisDialog", u"Basic", None))
#if QT_CONFIG(tooltip)
        self.medianFilterCheckBox.setToolTip(QCoreApplication.translate("analysisDialog", u"<Link to CLI description>", None))
#endif // QT_CONFIG(tooltip)
        self.medianFilterCheckBox.setText(QCoreApplication.translate("analysisDialog", u"Smoothen curves by median filtering", None))
#if QT_CONFIG(tooltip)
        self.medianFilterSpinBox.setToolTip(QCoreApplication.translate("analysisDialog", u"<Link to CLI description>", None))
#endif // QT_CONFIG(tooltip)
        self.medianFilterSpinBox.setPrefix("")
#if QT_CONFIG(tooltip)
        self.shrinkCheckBox.setToolTip(QCoreApplication.translate("analysisDialog", u"<Link to CLI description>", None))
#endif // QT_CONFIG(tooltip)
        self.shrinkCheckBox.setText(QCoreApplication.translate("analysisDialog", u"Shrink data", None))
#if QT_CONFIG(tooltip)
        self.shrinkDoubleSpinBox.setToolTip(QCoreApplication.translate("analysisDialog", u"Set minimal signal-to-noise ratio", None))
#endif // QT_CONFIG(tooltip)
        self.shrinkDoubleSpinBox.setPrefix("")
        self.filterWindowSizeLabel.setText(QCoreApplication.translate("analysisDialog", u"Filter window size, deg", None))
        self.shrinkNewdTValueLabel.setText(QCoreApplication.translate("analysisDialog", u"New dT value", None))
        self.labelTempRangeMin.setText(QCoreApplication.translate("analysisDialog", u"Remove from curve start (in X-axis units)", None))
        self.labelTempRangeMax.setText(QCoreApplication.translate("analysisDialog", u"Remove from curve end (in X-axis units)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.preprocessTab), QCoreApplication.translate("analysisDialog", u"Preprocess", None))
#if QT_CONFIG(tooltip)
        self.savgolSpinBox.setToolTip(QCoreApplication.translate("analysisDialog", u"<Link to CLI description>", None))
#endif // QT_CONFIG(tooltip)
        self.savgolSpinBox.setPrefix("")
        self.savgolLabel.setText(QCoreApplication.translate("analysisDialog", u"Savitzky-Golay window size (for derivative), X-axis units", None))
        self.baselineFitLabel.setText(QCoreApplication.translate("analysisDialog", u"Data length for baseline fit estimation, X-axis units", None))
#if QT_CONFIG(tooltip)
        self.baselineFitSpinBox.setToolTip(QCoreApplication.translate("analysisDialog", u"<Link to CLI description>", None))
#endif // QT_CONFIG(tooltip)
        self.baselineFitSpinBox.setPrefix("")
        self.baselineBoundsLabel.setText(QCoreApplication.translate("analysisDialog", u"Baseline bounds (n*stdev)", None))
#if QT_CONFIG(tooltip)
        self.baselineBoundsSpinbox.setToolTip(QCoreApplication.translate("analysisDialog", u"<Link to CLI description>", None))
#endif // QT_CONFIG(tooltip)
        self.baselineBoundsSpinbox.setPrefix("")
        self.dCpLabel.setText(QCoreApplication.translate("analysisDialog", u"Heat capacity change (dCp), J/mol/K", None))
#if QT_CONFIG(tooltip)
        self.dCpSpinBox.setToolTip(QCoreApplication.translate("analysisDialog", u"<Link to CLI description>", None))
#endif // QT_CONFIG(tooltip)
        self.dCpSpinBox.setPrefix("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.miscTab), QCoreApplication.translate("analysisDialog", u"Misc", None))
    # retranslateUi

