# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QDockWidget, QHeaderView, QLabel,
    QMainWindow, QMenu, QMenuBar, QPlainTextEdit,
    QSizePolicy, QStatusBar, QTableWidget, QTableWidgetItem,
    QToolBar, QVBoxLayout, QWidget)
from . import resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1221, 779)
        self.actionLoad = QAction(MainWindow)
        self.actionLoad.setObjectName(u"actionLoad")
        icon = QIcon()
        icon.addFile(u":/fileopen.svgz", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionLoad.setIcon(icon)
        self.actionExport = QAction(MainWindow)
        self.actionExport.setObjectName(u"actionExport")
        icon1 = QIcon()
        icon1.addFile(u":/export.svgz", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionExport.setIcon(icon1)
        self.actionExport.setVisible(False)
        self.actionQuit = QAction(MainWindow)
        self.actionQuit.setObjectName(u"actionQuit")
        icon2 = QIcon()
        icon2.addFile(u":/filequit.svgz", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionQuit.setIcon(icon2)
        self.actionAnalysis = QAction(MainWindow)
        self.actionAnalysis.setObjectName(u"actionAnalysis")
        icon3 = QIcon()
        icon3.addFile(u":/analysis.svgz", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionAnalysis.setIcon(icon3)
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionDeselectAll = QAction(MainWindow)
        self.actionDeselectAll.setObjectName(u"actionDeselectAll")
        icon4 = QIcon()
        icon4.addFile(u":/clear.svgz", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionDeselectAll.setIcon(icon4)
        self.actionEdit_layout = QAction(MainWindow)
        self.actionEdit_layout.setObjectName(u"actionEdit_layout")
        icon5 = QIcon()
        icon5.addFile(u":/editlayout.svgz", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionEdit_layout.setIcon(icon5)
        self.actionEdit_layout.setVisible(False)
        self.actionNew = QAction(MainWindow)
        self.actionNew.setObjectName(u"actionNew")
        icon6 = QIcon()
        icon6.addFile(u":/filenew.svgz", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionNew.setIcon(icon6)
        self.actionHelp = QAction(MainWindow)
        self.actionHelp.setObjectName(u"actionHelp")
        icon7 = QIcon()
        icon7.addFile(u":/help.svgz", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionHelp.setIcon(icon7)
        self.actionSave_as_JSON = QAction(MainWindow)
        self.actionSave_as_JSON.setObjectName(u"actionSave_as_JSON")
        icon8 = QIcon()
        icon8.addFile(u":/filesaveas.svgz", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionSave_as_JSON.setIcon(icon8)
        self.actionActions = QAction(MainWindow)
        self.actionActions.setObjectName(u"actionActions")
        icon9 = QIcon()
        icon9.addFile(u":/preferences.svgz", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionActions.setIcon(icon9)
        self.actionPrtSc = QAction(MainWindow)
        self.actionPrtSc.setObjectName(u"actionPrtSc")
        icon10 = QIcon()
        icon10.addFile(u":/savewindow.svgz", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionPrtSc.setIcon(icon10)
        self.actionSelectAll = QAction(MainWindow)
        self.actionSelectAll.setObjectName(u"actionSelectAll")
        icon11 = QIcon()
        icon11.addFile(u":/selectall.svgz", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionSelectAll.setIcon(icon11)
        self.actionCite_MoltenProt = QAction(MainWindow)
        self.actionCite_MoltenProt.setObjectName(u"actionCite_MoltenProt")
        icon12 = QIcon()
        icon12.addFile(u":/cite.svgz", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionCite_MoltenProt.setIcon(icon12)
        self.actionShowHideProtocol = QAction(MainWindow)
        self.actionShowHideProtocol.setObjectName(u"actionShowHideProtocol")
        self.actionShowHideProtocol.setCheckable(True)
        icon13 = QIcon()
        icon13.addFile(u":/protocol.svgz", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionShowHideProtocol.setIcon(icon13)
        self.actionFont = QAction(MainWindow)
        self.actionFont.setObjectName(u"actionFont")
        icon14 = QIcon()
        icon14.addFile(u":/font.svgz", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionFont.setIcon(icon14)
        self.actionLoad_sample_data = QAction(MainWindow)
        self.actionLoad_sample_data.setObjectName(u"actionLoad_sample_data")
        self.actionLoad_sample_data.setIcon(icon)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setMinimumSize(QSize(1122, 535))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1221, 27))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuSettings = QMenu(self.menubar)
        self.menuSettings.setObjectName(u"menuSettings")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.fileToolBar = QToolBar(MainWindow)
        self.fileToolBar.setObjectName(u"fileToolBar")
        MainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.fileToolBar)
        self.actionToolBar = QToolBar(MainWindow)
        self.actionToolBar.setObjectName(u"actionToolBar")
        MainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.actionToolBar)
        self.protocolDockWidget = QDockWidget(MainWindow)
        self.protocolDockWidget.setObjectName(u"protocolDockWidget")
        self.protocolDockWidget.setEnabled(True)
        self.protocolDockWidget.setMinimumSize(QSize(920, 144))
        self.protocolDockWidget.setAllowedAreas(Qt.BottomDockWidgetArea)
        self.protocolDockWidgetContents = QWidget()
        self.protocolDockWidgetContents.setObjectName(u"protocolDockWidgetContents")
        self.verticalLayout = QVBoxLayout(self.protocolDockWidgetContents)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.runAnalysisCounterLabel = QLabel(self.protocolDockWidgetContents)
        self.runAnalysisCounterLabel.setObjectName(u"runAnalysisCounterLabel")

        self.verticalLayout.addWidget(self.runAnalysisCounterLabel)

        self.protocolPlainTextEdit = QPlainTextEdit(self.protocolDockWidgetContents)
        self.protocolPlainTextEdit.setObjectName(u"protocolPlainTextEdit")
        self.protocolPlainTextEdit.setAcceptDrops(False)
        self.protocolPlainTextEdit.setReadOnly(True)

        self.verticalLayout.addWidget(self.protocolPlainTextEdit)

        self.protocolDockWidget.setWidget(self.protocolDockWidgetContents)
        MainWindow.addDockWidget(Qt.DockWidgetArea.BottomDockWidgetArea, self.protocolDockWidget)
        self.miscToolBar = QToolBar(MainWindow)
        self.miscToolBar.setObjectName(u"miscToolBar")
        MainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.miscToolBar)
        self.heatmapDockWidget = QDockWidget(MainWindow)
        self.heatmapDockWidget.setObjectName(u"heatmapDockWidget")
        self.heatmapDockWidgetContents = QWidget()
        self.heatmapDockWidgetContents.setObjectName(u"heatmapDockWidgetContents")
        self.heatmapDockWidget.setWidget(self.heatmapDockWidgetContents)
        MainWindow.addDockWidget(Qt.DockWidgetArea.LeftDockWidgetArea, self.heatmapDockWidget)
        self.tableDockWidget = QDockWidget(MainWindow)
        self.tableDockWidget.setObjectName(u"tableDockWidget")
        self.tableDockWidgetContents = QWidget()
        self.tableDockWidgetContents.setObjectName(u"tableDockWidgetContents")
        self.verticalLayout_2 = QVBoxLayout(self.tableDockWidgetContents)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.tableWidget = QTableWidget(self.tableDockWidgetContents)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setAlternatingRowColors(True)

        self.verticalLayout_2.addWidget(self.tableWidget)

        self.tableDockWidget.setWidget(self.tableDockWidgetContents)
        MainWindow.addDockWidget(Qt.DockWidgetArea.LeftDockWidgetArea, self.tableDockWidget)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addAction(self.actionLoad_sample_data)
        self.menuFile.addAction(self.actionSave_as_JSON)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionAnalysis)
        self.menuSettings.addAction(self.actionEdit_layout)
        self.menuSettings.addAction(self.actionSelectAll)
        self.menuSettings.addAction(self.actionDeselectAll)
        self.menuSettings.addAction(self.actionActions)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionCite_MoltenProt)
        self.menuHelp.addAction(self.actionAbout)
        self.fileToolBar.addAction(self.actionNew)
        self.fileToolBar.addAction(self.actionLoad)
        self.fileToolBar.addAction(self.actionSave_as_JSON)
        self.fileToolBar.addAction(self.actionExport)
        self.fileToolBar.addAction(self.actionQuit)
        self.fileToolBar.addSeparator()
        self.actionToolBar.addAction(self.actionAnalysis)
        self.actionToolBar.addAction(self.actionSelectAll)
        self.actionToolBar.addAction(self.actionDeselectAll)
        self.miscToolBar.addAction(self.actionShowHideProtocol)
        self.miscToolBar.addAction(self.actionEdit_layout)
        self.miscToolBar.addAction(self.actionActions)
        self.miscToolBar.addAction(self.actionPrtSc)
        self.miscToolBar.addAction(self.actionFont)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MoltenProt", None))
        self.actionLoad.setText(QCoreApplication.translate("MainWindow", u"Load", None))
#if QT_CONFIG(shortcut)
        self.actionLoad.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+L", None))
#endif // QT_CONFIG(shortcut)
        self.actionExport.setText(QCoreApplication.translate("MainWindow", u"Export", None))
#if QT_CONFIG(shortcut)
        self.actionExport.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+E", None))
#endif // QT_CONFIG(shortcut)
        self.actionQuit.setText(QCoreApplication.translate("MainWindow", u"Quit", None))
#if QT_CONFIG(shortcut)
        self.actionQuit.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
        self.actionAnalysis.setText(QCoreApplication.translate("MainWindow", u"Analysis", None))
#if QT_CONFIG(shortcut)
        self.actionAnalysis.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+A", None))
#endif // QT_CONFIG(shortcut)
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About MoltenProt", None))
#if QT_CONFIG(shortcut)
        self.actionAbout.setShortcut(QCoreApplication.translate("MainWindow", u"F1", None))
#endif // QT_CONFIG(shortcut)
        self.actionDeselectAll.setText(QCoreApplication.translate("MainWindow", u"Deselect All", None))
#if QT_CONFIG(tooltip)
        self.actionDeselectAll.setToolTip(QCoreApplication.translate("MainWindow", u"Clear all samples selection.", None))
#endif // QT_CONFIG(tooltip)
        self.actionEdit_layout.setText(QCoreApplication.translate("MainWindow", u"Edit layout", None))
        self.actionNew.setText(QCoreApplication.translate("MainWindow", u"New", None))
#if QT_CONFIG(tooltip)
        self.actionNew.setToolTip(QCoreApplication.translate("MainWindow", u"Start new instance of program", None))
#endif // QT_CONFIG(tooltip)
        self.actionHelp.setText(QCoreApplication.translate("MainWindow", u"MoltenProt help", None))
        self.actionSave_as_JSON.setText(QCoreApplication.translate("MainWindow", u"Save as JSON", None))
        self.actionActions.setText(QCoreApplication.translate("MainWindow", u"Settings", None))
#if QT_CONFIG(tooltip)
        self.actionActions.setToolTip(QCoreApplication.translate("MainWindow", u"MoltenProt Settings", None))
#endif // QT_CONFIG(tooltip)
        self.actionPrtSc.setText(QCoreApplication.translate("MainWindow", u"PrtSc", None))
#if QT_CONFIG(tooltip)
        self.actionPrtSc.setToolTip(QCoreApplication.translate("MainWindow", u"Save MoltenProt Main window as png file.", None))
#endif // QT_CONFIG(tooltip)
        self.actionSelectAll.setText(QCoreApplication.translate("MainWindow", u"Select All", None))
#if QT_CONFIG(tooltip)
        self.actionSelectAll.setToolTip(QCoreApplication.translate("MainWindow", u"Press to select all samples", None))
#endif // QT_CONFIG(tooltip)
        self.actionCite_MoltenProt.setText(QCoreApplication.translate("MainWindow", u"Cite MoltenProt", None))
        self.actionShowHideProtocol.setText(QCoreApplication.translate("MainWindow", u"P", None))
#if QT_CONFIG(tooltip)
        self.actionShowHideProtocol.setToolTip(QCoreApplication.translate("MainWindow", u"Press to Show/Hide the Protocol window.", None))
#endif // QT_CONFIG(tooltip)
        self.actionFont.setText(QCoreApplication.translate("MainWindow", u"Font", None))
#if QT_CONFIG(tooltip)
        self.actionFont.setToolTip(QCoreApplication.translate("MainWindow", u"Select font family and font size.", None))
#endif // QT_CONFIG(tooltip)
        self.actionLoad_sample_data.setText(QCoreApplication.translate("MainWindow", u"Load sample data", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuSettings.setTitle(QCoreApplication.translate("MainWindow", u"Actions", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.fileToolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.actionToolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"Analysis", None))
        self.protocolDockWidget.setWindowTitle(QCoreApplication.translate("MainWindow", u"Protocol Window", None))
        self.runAnalysisCounterLabel.setText(QCoreApplication.translate("MainWindow", u"runAnalysisCounterTextLabel", None))
#if QT_CONFIG(tooltip)
        self.protocolPlainTextEdit.setToolTip(QCoreApplication.translate("MainWindow", u"Here various messages will be printed.", None))
#endif // QT_CONFIG(tooltip)
        self.miscToolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"Miscelenious", None))
        self.heatmapDockWidget.setWindowTitle(QCoreApplication.translate("MainWindow", u"Heatmap", None))
        self.tableDockWidget.setWindowTitle(QCoreApplication.translate("MainWindow", u"Displayed samples", None))
    # retranslateUi

